Description of lap_structure
Home > functions > lap_structure.m
lap_structure
PURPOSE
LAP_STUCTURE Creates a structure of the Track entered
SYNOPSIS
function [ indexa ] = lap_structure(filename, vectors_merge_no,angles_block_no)
DESCRIPTION
LAP_STUCTURE Creates a structure of the Track entered
  filename -> single track data for extrapolating results
   merge_no -> number of points to merge (EVEN)
   block -> number of direction_vectors to merge-overlap
CROSS-REFERENCE INFORMATION
This function calls:
RacerToMatlab Convert Racer text to variable arrays
angles ANGLES Find the angle in a block of direction vectors using weighted
anglesOntrack ANGLESONTRACK split track into angles and their direction vectors
vectors VECTORS create vectors on 3d consequtive points inserted
This function is called by:
SOURCE CODE
function [ indexa ] = lap_structure(filename, vectors_merge_no,angles_block_no)
%LAP_STUCTURE Creates a structure of the Track entered
%  filename -> single track data for extrapolating results
%   merge_no -> number of points to merge (EVEN)
%   block -> number of direction_vectors to merge-overlap
[~,~, ~, ~,~,~,~,~,~, position3d, ~,~, ~,~,~,~] = RacerToMatlab(filename);
[direction_vectors pos] = vectors(position3d, vectors_merge_no);
[angles_last ,~,~,~] = angles(direction_vectors,angles_block_no);
[indexa]= anglesOntrack(angles_last, direction_vectors, position3d, pos, vectors_merge_no, angles_block_no);
end