Description of overlap_average
Home > functions > overlap_average.m
overlap_average
PURPOSE
OVERLAP_AVERAGE Average the data give by creating overlapping decimations
SYNOPSIS
function [ data, variance ] = overlap_average(data, no, overlap)
DESCRIPTION
OVERLAP_AVERAGE Average the data give by creating overlapping decimations
of the data
 data: Any nxm matrix to be averaged
 no  : Number of samples to average
 overlap: Number of samples to overlap each time (overlap < no)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
user_inputs USER_INPUTS Creates user input model for a certain track
user_inputs_only_on_track USER_INPUTS_ONLY_ON_TRACK Summary of this function goes here
vectors VECTORS create vectors on 3d consequtive points inserted
SOURCE CODE
function [ data, variance ] = overlap_average(data, no, overlap)
%OVERLAP_AVERAGE Average the data give by creating overlapping decimations
%of the data
% data: Any nxm matrix to be averaged
% no  : Number of samples to average
% overlap: Number of samples to overlap each time (overlap < no)
    mn=[];
    vr=[];
    for t = 1:overlap:size(data,2)-no
         matrix = data(:,t:t+no);
         m = mean(matrix,2);
         mn= [mn m];
         v = var(matrix');
         vr = [vr v'];
    end
    data =mn;
    variance= vr;
end