Description of RacerToMatlab
Home > functions > RacerToMatlab.m
RacerToMatlab
PURPOSE
Convert Racer text to variable arrays
SYNOPSIS
function [A,check, speed, brakes,gas,clutch,gear,lapdistance,time, position3d, acceleration3d,steering, gForceLat,gForceLong,handbrake,lapTime] = RacerToMatlab(filename, instance)
DESCRIPTION
Convert Racer text to variable arrays
Author: Theos
22/02/2012
Text file data:Speed,brakes,gas,clutch,gear,distance,time, x, y ,z, x-acc, y-acc,z-acc,steering
CROSS-REFERENCE INFORMATION
This function calls:
loadRacerFile LOADRACERFILE Loads the particular file creater from Racer
This function is called by:
RacerToMatlabPlotting Convert Racer text to variable arrays + plots them
create_training_data CREATE_TRAINING_DATA Convert Racer text file to multiple files according to track data
lap_structure LAP_STUCTURE Creates a structure of the Track entered
user_inputs USER_INPUTS Creates user input model for a certain track
user_inputs_only_on_track USER_INPUTS_ONLY_ON_TRACK Summary of this function goes here
user_structure USER_STRUCTURE Creates a structure of the Track entered
SOURCE CODE
%Convert Racer text to variable arrays
%Author: Theos
%22/02/2012
%Text file data:Speed,brakes,gas,clutch,gear,distance,time, x, y ,z, x-acc, y-acc,z-acc,steering
%if instance is 'y' then file name is already a matrix
function [A,check, speed, brakes,gas,clutch,gear,lapdistance,time, position3d, acceleration3d,steering, gForceLat,gForceLong,handbrake,lapTime] = RacerToMatlab(filename, instance)
    if ~exist('instance', 'var')
        instance = 'n';
    end
    if strcmp(instance,'n')
    A = loadRacerFile( filename );
    else
    A= filename;
    end
    check= A(1,:);
    speed = A(2,:);
    brakes = A(3,:);
    gas = A(4,:);
    clutch = A(5,:);
    gear = A(6,:);
    lapdistance = A(7,:);
    time = A(8,:);
    position3d = A(9:11,:);
    acceleration3d = A(12:14,:);
    steering = A(15,:);
    gForceLat = A(16,:);
    gForceLong= A(17,:);
    handbrake = A(18,:);
    lapTime = max(A(19,:));
end